services:
#  my_app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    image: app
#    container_name: app
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: storage
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"